parameters_local:
    db_driver: pdo_mysql
    db_host: #database host here
    db_port: null
    db_name: #database name here
    db_user: root
    db_password: null
    mail_transport: smtp
    mail_host: 127.0.0.1
    mail_user: null
    mail_password: null
    locale: fr
    secret: #secret key
    
parameters_host:
    db_driver: pdo_mysql
    db_host: #database host here
    db_port: null
    db_name: #db name 
    db_user: #db id 
    db_password: #db pass
    mail_transport: smtp
    mail_host: #mail host here
    mail_user: null
    mail_password: null
    locale: fr
    secret: #secret key
